// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullArrayIntTypeEnum int
const (

	 UnionNullArrayIntTypeEnumNull UnionNullArrayIntTypeEnum = 0

	 UnionNullArrayIntTypeEnumArrayInt UnionNullArrayIntTypeEnum = 1

)

type UnionNullArrayInt struct {

	Null *types.NullVal

	ArrayInt []int32

	UnionType UnionNullArrayIntTypeEnum
}

func writeUnionNullArrayInt(r *UnionNullArrayInt, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullArrayIntTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullArrayIntTypeEnumArrayInt:
		return writeArrayInt(r.ArrayInt, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullArrayInt")
}

func NewUnionNullArrayInt() *UnionNullArrayInt {
	return &UnionNullArrayInt{}
}

func (_ *UnionNullArrayInt) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullArrayInt) SetLong(v int64) { 
	r.UnionType = (UnionNullArrayIntTypeEnum)(v)
}
func (r *UnionNullArrayInt) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ArrayInt = make([]int32, 0)
		
		
		return (*ArrayIntWrapper)(&r.ArrayInt)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayInt) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayInt) Finalize()  { }
